### ISSUE TITLE
Spring Cloud Gateway学习

### ISSUE THREAD

**Issue by liujiusheng** [liujiusheng/blog#210]
Spring Cloud Gateway的使用主要是修改application.yml配置文件，内容如下：
```
spring:
  cloud:
    gateway:
      routes:
      - id: prefixpath_route
        uri: https://example.org
        predicates:

        filters:
        - PrefixPath=/mypath
```
下面这一节是固定的
```
spring:
  cloud:
    gateway:
```

routes代表本定义的路由规则，可以用很多个。

其中id是这个规则的命名，没什么太大实际意义。

uri是要转发到的地址。uri中通常会有`lb://`的字样，是指到注册中心去取服务。

predicates是指断言，是各种路由的匹配规则，可以根据路由、header等进行匹配，规则很丰富。

filters就是指要对发送到目的地和目的地返回的数据的路由、header等进行处理。
